---
snapshot:
  name_template: "{{ incminor .Version }}-prerelease"

builds:
  - main: .
    binary: protoc-gen-go-hashpb
    id: "protoc-gen-go-hashpb"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/cerbos/protoc-gen-go-hashpb/internal/generator.Version={{.Version}}
checksum:
  name_template: "checksums.txt"
